### ISSUE TITLE
German language support

### ISSUE THREAD

**Issue by dgrammlich** [markdumay/hugo-theme-hinode-child#40]
Hey Mark,

thank you for this pretty theme. ☺️ 
I am currently setting up the Hinode child theme for my website. At the moment, I have only content in one language, German. I fail to get it working.

I cloned this repository and copied the `config` folder to its root to make my edits.
`config/_default/config.toml`
```toml
languageCode = "en-us"
# Multilingual
defaultContentLanguage = "de"
#disableLanguages = ["en", "nl"]
#defaultContentLanguageInSubdir = true
#enableMissingTranslationPlaceholders = true
```
`config/_default/languages.toml`
```toml
[de]
    languageName = "Deutsch"
    contentDir = "content/de"
    weight = 1
    [de.params]
        introTitle = "My website"
```
Up to this point, it works. The `de.params` values are shown on the website and the links are without `/de` in it, showing the content from `content/de`. Now I want to also add `i18n` translations for all the other stuff. I created a folder `i18n` in the project root and copied the `i18n/en.yaml` file from the Hinode main theme as `de.yaml` into it. I made my edits and tried to build the website, but the following error occurs:
```bash
INFO 2022/12/11 11:30:12 Translation func for language de not found, use default.
INFO 2022/12/11 11:30:12 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
```
From there I tried a lot of stuff, searched the Internet, but I do not see what I've missed. 

I would love to contribute the finished `de.yaml` file to the main theme after seeing it rendered in the website.

Thanks in advance for your help.
Daniela
